-- CreateTable
CREATE TABLE `TimeLog` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `StartTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `EndTime` DATETIME(3) NULL,
    `duration` INTEGER NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
